default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: student_manager_backend_development

test:
  <<: *default
  database: student_manager_backend_test

production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  cache:
    <<: *default
    url: <%= ENV['DATABASE_URL'].gsub('student_manager_backend_production', 'student_manager_backend_production_cache') %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    url: <%= ENV['DATABASE_URL'].gsub('student_manager_backend_production', 'student_manager_backend_production_queue') %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    url: <%= ENV['DATABASE_URL'].gsub('student_manager_backend_production', 'student_manager_backend_production_cable') %>
    migrations_paths: db/cable_migrate
